### ISSUE TITLE
wanted plugins

### ISSUE THREAD

**Issue by scoutrul** [jh3y/gulp-boilerplate#10]
Hello! 
It is gonna be great if you will add plugins 'kouto-swiss' and 'typographic'. Thank you.

**Comment by jh3y** [comment]
Hey @scoutrul 

Thanks for contributing. It's unlikely I will be adding extra plugins and packages other than those included. This repo is intended as a starting point and a boilerplate for creating projects using `gulp`.

My suggestion would be to fork the repo and tailor it to your specific needs 👍 

@jh3y
