### ISSUE TITLE
Deploy images

### ISSUE THREAD

**Issue by scoutrul** [jh3y/gulp-boilerplate#12]
Hello here!
I have a problem with deploying images to the gh-pages.
Can u explain me how to do this right? How to config folders?

**Comment by scoutrul** [comment]
Do you here?

**Comment by jh3y** [comment]
Hey @scoutrul 

You would need to configure sources for your assets and implement a task that publishes assets to your output folder and then integrate this with the other tasks that would run on a deployment. The simplest task for handling assets would be simply copying from source to output. Something like;

```js
gulp.task('publish:images', function() {
  return gulp.src('src/assets/images/**/*.*')
    .pipe(gulp.dest('public/images');
})
```
Hope that helps!

**Comment by scoutrul** [comment]
Yes, thank you!
