### ISSUE TITLE
Compile Scripts Gets Slow Adding Browserify

### ISSUE THREAD

**Issue by harrisonfm** [jh3y/gulp-boilerplate#17]
So I added Browserify into the compile scripts task, but just including a basic call to it in Scripts - Compile slows down to about 9 seconds. I'm only working with jQuery at the moment.

I wonder if there's a better way to add it than just throwing a call to browserify as a pipe in compile. Any guidance to improve performance would be very appreciated.

**Comment by jh3y** [comment]
Hey @harrisonfm,

With `browserify` it's best to create a different form of `script` compilation task. What does your current task look like?

I've had good experience with creating something like the following(_a stripped down version that should help get you up and running with `browserify` working_);

```javascript
var gulp = require('gulp'),
    browserify = require('browserify'),
    source = require('vinyl-source-stream'),
    buffer = require('vinyl-buffer'),
    plugins = require('gulp-load-plugins')();

gulp.task('compile:scripts', () => {
    var b = browserify({
      entries: [
        './src/script/app.js'
      ],
      transform: 'babelify',
      extensions: '.js',
    });

    return b.bundle()
      .pipe(plugins.plumber())
      .pipe(source('<<PROJECT_NAME>>.js'))
      .pipe(buffer())
      .pipe(gulp.dest('/public/js))
})
```
You start by creating your bundle and then creating a stream of it to use with `gulp` 👍 

Hope that helps you out!

**Comment by harrisonfm** [comment]
Nice. Thank you for the assist here.

**Comment by jh3y** [comment]
No worries @harrisonfm, glad I could help! 😄
