### ISSUE TITLE
TypeError: _gulp2.default.parallel is not a function

### ISSUE THREAD

**Issue by scoutrul** [jh3y/gulp-boilerplate#26]
Thanks for this boilerplate, but it can't start with this package.
`TypeError: _gulp2.default.parallel is not a function
`
You should install gulpjs/gulp.git#4.0 before. And it will work fine~!
Update the docs ;)

**Comment by jh3y** [comment]
Hi @scoutrul 👋 

I can't replicate this issue 😢  there may be cached dependencies.

On a fresh install, there will be no issues with `gulpjs/gulp#4.0`. I can try this with 

```shell
rm -rf node_modules
yarn cache clean
yarn
```

The docs have no mention of which package to install as this is handled via `package.json` and the `.lock` files. Therefore, the docs would not need updating.

What I will likely do though is upgrade the package to `^4.0.0` via `yarn add --dev gulp@next` 👍 

@jh3y
