### ISSUE TITLE
@babel/register

### ISSUE THREAD

**Issue by cagcak** [jh3y/gulp-boilerplate#30]
At the very top of the log output:
`Failed to load external module @babel/register`
As a side note:
`npm i babel-register`
does not correct the issue.
I've been trying to solve this problem, no luck yet.

**Comment by jh3y** [comment]
Hey @cagcak 👋 

It's not seen as an issue. It doesn't affect how `gulp` runs. The log details the fallback behavior of loading the module. Details are here: [#1631](https://github.com/gulpjs/gulp/issues/1631) 

@jh3y
