### ISSUE TITLE
Revisit task names

### ISSUE THREAD

**Issue by jh3y** [jh3y/gulp-boilerplate#4]
Revisit task names so things are consistently named by `action:sourceType`.

For example; currently there are things like `markup:watch` and `styles:compile` but it would be better if things were named the other way round.

Intuitively, I would think `compile:script` and `lint:script` or `watch:markup` and not the other way round.

@jh3y

**Comment by RzvnB** [comment]
Gonna have a take at this.

**Comment by jh3y** [comment]
Feel free :smile:

Check for consistency with `gulp -T` after. Was just using it for a different project and keep typing task names which don't exist 😂

**Comment by RzvnB** [comment]
PR #6
