### ISSUE TITLE
Task 'markup:compile' is not in your gulpfile

### ISSUE THREAD

**Issue by scoutrul** [jh3y/gulp-boilerplate#8]
Hello! Thanks for this boilerplate, but here is a error while I trying change .pug file.
'Task 'markup:compile' is not in your gulpfile'

Without any code changes.

**Comment by jh3y** [comment]
Hey @scoutrul 😄 

Thanks for contributing, that's a great spot, you're right!

It's looking for `markup:compile` when the task is actually named `compile:markup`. I've fixed this and updated the version 👍 

In future, I will look to implement a better way to manage the task names across files.

Hope that helps and thanks again!

**Comment by scoutrul** [comment]
Thank you! 
Waiting for future updates.

I need easy and fast gulp-boilerplate with pug, stylus, babel, and all cosmetics, hope it gonna be your project. GL

**Comment by jh3y** [comment]
Hey @scoutrul ,

No worries 😄  Any other improvements or scenarios you'd like to see, don't hesitate to open another issue 👍 

@jh3y

**Comment by scoutrul** [comment]
Task 'styles:compile' is not in your gulpfile

**Comment by jh3y** [comment]
Hey @scoutrul 

Really sorry about that. I've put together a solution for this task name issue mentioned in #9 by utilising `key-mirror`. This problem should be resolved now in the new version `3.3.0` 👍 

Thanks again for contributing!

@jh3y
